name: prime-cache-15b2e38

on:
  push:
  workflow_dispatch:

jobs:
  cache-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: cache-15b2e38

      - name: prime-cache-15b2e38
        run: |
          echo "Cache hit? ${{ steps.cache.outputs.cache-hit }}"
      - name: 23f2002999@ds.study.iitm.ac.in
        run: echo "Hello, world!"